# Configuración PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/motorgestion
spring.datasource.username=dit
spring.datasource.password=dit
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.address=0.0.0.0
server.port=9000

